version: "3.9"

services:
  fastapi:
    build: ./fastapi_app
    ports:
      - "8000:8000"
    networks:
      - app-network

  streamlit:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
